#ifndef NEMO_PROTO_IDS_H
#define NEMO_PROTO_IDS_H

#define NDPI_PROTOCOL_UNKNOWN 0
#define NDPI_PROTOCOL_DNS 1
#define NDPI_PROTOCOL_HTTP 2
#define NDPI_PROTOCOL_TLS 3
#define NDPI_PROTOCOL_QUIC 4
#define NDPI_PROTOCOL_MAIL_IMAP 5
#define NDPI_PROTOCOL_MAIL_SMTP 6

#endif
