apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    ndkVersion "28.2.13676358"

    defaultConfig {
        applicationId "com.nemo.networkconditioner"
        minSdkVersion 21
        compileSdk 35
        targetSdk 35
        versionCode 1
        versionName "1.0.2"
        
        resourceConfigurations += ["en"]
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            applicationIdSuffix '.debug'
        }
    }

    buildFeatures {
        buildConfig = true
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/jni/CMakeLists.txt')
            version "3.22.1"
        }
    }

    compileOptions {
        encoding "UTF-8"
        coreLibraryDesugaringEnabled true // support devices running older Java versions
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    namespace 'com.nemo.networkconditioner'

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            def suffix = (variant.buildType.name == "release") ? "" : "-${variant.buildType.name}"
            outputFileName = "nemo-v${variant.versionName}${suffix}.apk"
        }
    }
}

dependencies {
// AndroidX
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

// Google
    implementation 'com.google.android.material:material:1.13.0'

// Third-party
    implementation 'cat.ereza:customactivityoncrash:2.4.0'
}
